In [14]:
"""
data_preprocess.ipynb
Created by ST Chien, 08/18/2019
"""
import scipy.io
import numpy as np
import pandas as pd

# read matLab file
mat_train_feature = scipy.io.loadmat("../Dataset/data_train.mat")
mat_train_label = scipy.io.loadmat("../Dataset/data_train_labels.mat")

In [15]:
# have a peek of the data...ooohhh it's...WUT THE FOOK IS THIS????
mat_train_label["data_train_labels"][0]

"""
After this experience of converting the training data, 
I think I know why the data provided this time is in mat file...
.csv file is uncompressed and is absurdly large
"""

array([1, 1, 1, ..., 8, 8, 8], dtype=uint8)

In [16]:
# convert whaterver is in the .mat file in to dataframe
trainingDataframe = pd.DataFrame(np.reshape(mat_train_feature["data_train"][0], (2048, 1)))
trainingLabel = pd.DataFrame(np.reshape(mat_train_label["data_train_labels"][0], (2048, 1)))
trainingLabel

      0
0     1
1     1
2     1
3     1
4     1
...  ..
2043  8
2044  8
2045  8
2046  8
2047  8

[2048 rows x 1 columns]

In [17]:
# convert the data to one dimentional array
for i in range(len(trainingDataframe)):
    row = trainingDataframe.loc[i].values[0]
    dimReducedRow = [value[0] for value in row]
    trainingDataframe.at[i, 0] = dimReducedRow

#trainingDataframe.head()

In [22]:
# add label and column name to dataframe
trainingDataframe["defect_type"] = mat_train_label["data_train_labels"][0]
trainingDataframe.columns = ["accelration", "defect_type"]
trainingDataframe.head()

                                         accelration  defect_type
0  [-17.62402648925945, -14.424026489259631, -22....            1
1  [-22.42402648925963, 1.5759735107403685, 30.37...            1
2  [3.1759735107402776, 14.37597351074055, -22.42...            1
3  [9.575973510740369, 11.175973510740278, 7.9759...            1
4  [-25.62402648925945, -12.824026489259722, -25....            1

In [27]:
trainingDataframe.to_csv("../Dataset/data_train.csv", index = False)

In [28]:
frame = pd.read_csv("../Dataset/data_train.csv")
frame

                                            accelration  defect_type
0     [-17.62402648925945, -14.424026489259631, -22....            1
1     [-22.42402648925963, 1.5759735107403685, 30.37...            1
2     [3.1759735107402776, 14.37597351074055, -22.42...            1
3     [9.575973510740369, 11.175973510740278, 7.9759...            1
4     [-25.62402648925945, -12.824026489259722, -25....            1
...                                                 ...          ...
2043  [6.056066894530886, 6.056066894530886, -17.943...            8
2044  [6.056066894530886, 6.056066894530886, 54.0560...            8
2045  [102.05606689453089, 182.0560668945309, 46.056...            8
2046  [30.056066894530886, 22.056066894530886, -137....            8
2047  [86.05606689453089, 110.05606689453089, 30.056...            8

[2048 rows x 2 columns]

In [1]:
"""
Convert the original data in to 2048*8192 dataframes
"""
def convertToRawDataframe(dataframe):
    table = []
    for i in range(len(trainingDataframe)):
        row = trainingDataframe.loc[i].values[0]
        dimReducedRow = [value[0] for value in row]
        table.append(dimReducedRow)
    return pd.DataFrame(table)

In [ ]:
"""
Save the whole data into a 2048 * 8192 csv
"""
rawTrainingDataframe = pd.DataFrame(np.reshape(mat_train_feature["data_train"][0], (2048, 1)))